[[items]]

[[items]]
id = "welcome"
html = "Welcome"
persist = true

[[items]]
id = "starting-soon"
html = "We will be starting soon"
persist = true

[[items]]
id = "1-bach-prelude-fugue"
html = "Claude Debussy<br>Suite Bergamasque, L. 75"
auto_next = true

[[items]]
id = "1.1-prelude"
html = "I. Prélude"
duration = 4

[[items]]
id = "1.2-menuet"
html = "II. Menuet"
duration = 4

[[items]]
id = "1.3-clair-de-lune"
html = "III. Clair de lune"
duration = 5.5

[[items]]
id = "1.4-passepied"
html = "IV. Passepied"
duration = 3

[[items]]
id = "2-naoumoff-desespoir"
html = "Emile Naoumoff<br>Désespoir, from Reminiscences (2002)"
duration = 2.5

[[items]]
id = "3-naoumoff-ruchenitsa"
html = "Emile Naoumoff<br>Ruchenitsa, from Danses Bulgares (1962)"
duration = 1

[[items]]
id = "4-medtner-forgotten-melodies"
html = "Nikolai Medtner<br>Forgotten Melodies, Op. 39"
auto_next = true

[[items]]
id = "4.1-canzona-matinata"
html = "4. Canzona Matinata"
duration = 4

[[items]]
id = "4.2-attacca-sonata-tragica"
html = "5. Attacca, Sonata Tragica"
duration = 10

[[items]]
id = "5-dupont"
html = "Gabriel Dupont<br>Selections from La Maison dans les dunes"
auto_next = true

[[items]]
id = "5.1-dans-le-dunes-par-un-clair-matin"
html = "I. Dans les dunes par un clair matin"
duration = 4

[[items]]
id = "5.2-voiles-sur-leau"
html = "II. Voiles sur l'eau"
duration = 4

[[items]]
id = "5.3-la-maison-du-souvenir"
html = "III. La maison du souvenir"
duration = 2.5

[[items]]
id = "5.4-mon-frere-le-vent-et-ma-soeur-la-pluie"
html = "IV. Mon frère le Vent et ma sœur la Pluie"
duration = 4

[[items]]
id = "6-scriabin-etude"
html = "Alexander Scriabin<br>Etude in B-Flat Minor, Op. 8, No. 11"
duration = 4

[[items]]
id = "7-chopin-sonata"
html = "Chopin<br>Sonata No. 3 in B Minor, Op. 52"
auto_next = true

[[items]]
id = "7.1-finale"
html = "IV. Finale: Presto non tanto"
duration = 4.5

[[items]]
id = "end"
html = "Thanks for watching"
persist = true
